### PR TITLE
Set an error message when the iframe doesn't load

### LINKED ISSUE #11: There is no error message when the iframe fails to load

### PR DESCRIPTION
**Pull request by DAreRodz**
Fixes #11

### CODE REVIEW

**Comment by luisherranz** [comment]
@DAreRodz what are the main reason/reasons the "iframe doesn't load"? Timeouts?

**Comment by DAreRodz** [comment]
Yes, the main reason is timeouts. I'm going to change the error message and increase the waiting time.

**Comment by luisherranz** [comment]
Thanks @DAreRodz! Let me know once you do.

**Comment by DAreRodz** [comment]
@luisherranz, you can check the code again.

**Review by luisherranz — APPROVED** [review]
Awesome. Thanks @DAreRodz

**Comment by luisherranz** [comment]
Feel free to release it.

**Pull request merged**
