### PR TITLE
Fixes in demo generation

### LINKED ISSUE #13: Improve demo generation
- [x] Remove all timeouts
- [x] Send demo URL to GTM
- [x] Show demo URL on the UI

### PR DESCRIPTION
**Pull request by DAreRodz**
Fixes #13

### CODE REVIEW

**Comment by luisherranz** [comment]
@DAreRodz is this PR supposed to be merged with `master` instead of `dev` for any reason?

**Comment by DAreRodz** [comment]
No, it's not. Changed to `dev`.

**Review by luisherranz — APPROVED** [review]
I have commented a couple of `console.logs` you forgot. Apart from that, everything seems fine.

**Comment by DAreRodz** [comment]
Perfect! Thank you @luisherranz.

**Comment by luisherranz** [comment]
I'll do the release.

**Pull request merged**
